name: Stable

on:
  push:
    branches:
      # Only run on stable branch merges
      - stable
  schedule:
    # Run at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
        java-package: jdk+fx
        distribution: adopt-hotspot
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ChunkyClPlugin
        path: build/libs/ChunkyClPlugin.jar
